import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { CardLayout } from "@/layouts";

export default function Card() {
  const { id } = useParams();
  const navigate = useNavigate();

  const card = {
    recipient: "Amaka",
    pickupLine: "Are you WiFi? Because I'm feeling the connection 😌",
    hasAirtime: true,
  };

  const [position, setPosition] = useState({ x: 0, y: 0 });

  const moveButton = () => {
    const maxX = window.innerWidth - 160;
    const maxY = window.innerHeight - 200;

    const randomX = Math.random() * maxX - maxX / 2;
    const randomY = Math.random() * maxY - maxY / 2;

    setPosition({
      x: randomX,
      y: randomY,
    });
  };

  const handleYes = () => {
    if (card.hasAirtime) {
      navigate(`/card/${id}/gift`);
    } else {
      navigate(`/card/${id}/success`);
    }
  };

  useEffect(() => {
    const interval = setInterval(() => {
      moveButton();
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  return (
    <CardLayout>
      <div className="text-center space-y-4">
        <h2 className="text-2xl font-bold">
          <span className="text-primary">{card.recipient}</span>, will you
          <br /> be my Valentine?
        </h2>

        <p className="text-muted max-w-md mx-auto">
          {card.pickupLine}
        </p>
      </div>

      <div className="relative mt-12 h-40 flex items-center justify-center">
        {/* YES BUTTON */}
        <button
          onClick={handleYes}
          className="btn bg-primary text-white px-8 py-3 rounded-xl font-semibold z-10"
        >
          Yes ❤️
        </button>

        {/* RUNNING NO BUTTON */}
        <button
          onMouseEnter={moveButton}
          onClick={moveButton}
          onTouchStart={moveButton}
          style={{
            transform: `translate(${position.x}px, ${position.y}px)`,
          }}
          className="btn bg-secondary border border-line text-main px-8 py-3 rounded-xl font-semibold absolute transition-all duration-300 ease-in-out"
        >
          No 💔
        </button>
      </div>

      <p className="text-xs text-muted mt-6 text-center">
        You can try, but destiny is faster 😏
      </p>

      <p className="text-xs text-muted mt-8 text-center leading-relaxed">
        Generated by{" "}
        <a
          href="https://useval.com"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary underline font-semibold"
        >
          Useval.com
        </a>{" "}
        <br />
        Built by{" "}
        <a
          href="https://github.com/efeurhobobullish"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary underline font-semibold"
        >
          Empire Tech
        </a>{" "}
        &{" "}
        <a
          href="https://github.com/learnwithjacksun"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary underline font-semibold"
        >
          Gift Jacksun
        </a>
      </p>
    </CardLayout>
  );
}
