import { useParams, useNavigate } from "react-router-dom";
import { useState } from "react";
import { CardLayout } from "@/layouts";

export default function Card() {
  const { id } = useParams();
  const navigate = useNavigate();

  // Mock data (later from API)
  const card = {
    recipient: "Amaka",
    pickupLine: "Are you WiFi? Because I'm feeling the connection 😌",
    hasAirtime: true,
  };

  const [noPos, setNoPos] = useState({ top: 0, left: 80 });

  const moveNoButton = () => {
    const randomTop = Math.random() * 400 - 200;
    const randomLeft = Math.random() * 400 - 200;

    setNoPos({
      top: randomTop,
      left: randomLeft,
    });
  };

  const handleYes = () => {
    if (card.hasAirtime) {
      navigate(`/card/${id}/gift`);
    } else {
      navigate(`/card/${id}/success`);
    }
  };

  return (
    <CardLayout>

          <div>
            <h2 className="text-2xl font-bold">
              <span className="text-primary">{card.recipient}</span>, will you
              be <br /> my Valentine?
            </h2>
            <p className="text-muted max-w-md mx-auto">{card.pickupLine}</p>
          </div>

          <div className="relative mt-10 h-32 flex items-center justify-center gap-6">
            {/* YES */}
            <button
              onClick={handleYes}
              className="btn bg-primary -translate-x-20 text-white px-8 py-3 rounded-xl font-semibold"
            >
              Yes ❤️
            </button>

            {/* NO (Evil button) */}
            <button
              onMouseEnter={moveNoButton}
              style={{
                transform: `translate(${noPos.left}px, ${noPos.top}px)`,
              }}
              className="btn bg-gray-200 text-gray-700 px-8 py-3 rounded-xl font-semibold transition-all duration-200 absolute z-100"
            >
              No 💔
            </button>
          </div>

          <p className="text-xs text-muted mt-6">
            You can try, but you can't escape destiny 😏
          </p>
          <p className="text-xs text-muted mt-6">
            Generated by{" "}
            <a
              href="https://useval.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline font-semibold"
            >
              Useval.com
            </a>{" "}
            &bull; Built by{" "}
            <a
              href="https://github.com/learnwithjacksun"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline font-semibold"
            >
              Gift Jacksun
            </a>
          </p>
    </CardLayout>
        
  );
}
